# Generated by Django 3.2.3 on 2021-05-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_belonging_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belonging',
            name='owner',
        ),
    ]
