# Generated by Django 3.2.3 on 2021-05-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="onder_by",
            new_name="by_company",
        ),
    ]
