# Generated by Django 3.2.3 on 2021-05-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ordered'), ('SHIPPED', 'In Shipping'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('PENDING', 'Pending')], default=('OPEN', 'Ordered'), max_length=20),
        ),
    ]
